Django/latest_movie/config/urls.py
from django.contrib import admin
from django.urls import path, include
from djan import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('movie_search/', views.search, name='search'),  # '/' 에 해당되는 path

    path('ranking/', views.ranking, name='ranking'),

    # / 링크가 오면 djan의 urls로
    path('',include('djan.urls')),
    
    path('common/', include('common.urls')),

]

Django/latest_movie/djan/urls.py
from django.urls import path

from . import views

#다른 프로젝트와 꼬이지 않게 이름지정
app_name='djan'

urlpatterns = [
    # '' 요청이 들어오면, view.py 의 main 메서드 연결
    path('', views.main, name='main'),

    # /숫자/ 링크를 입력하면, view.py 의 detail 메서드 연결
    path('<str:movie_code>/', views.detail ,name='detail'),

    # /숫자/vote/ 링크를 입력하면, view.py 의 vote 메서드 연결
    path('<str:movie_code>/vote/', views.vote, name='vote'),
    
    # /answer/create/숫자/ 링크를 입력하면, view.py 의 answer_create 메서드 연결
    # 이건 보통 링크를 입력해 접속하지 않고 투표하면 자동으로 이동한다. 
    path('answer/create/<str:movie_code>/', views.answer_create, name='answer_create'),
]

Django/latest_movie/djan/models.py
from django.db import models
# 사용자 모델로 회원가입시 데이터 저장 등에 사용
from django.conf import settings
from django.db import models
from django.utils import timezone
import datetime
from django.contrib import admin
from psycopg2 import IntegrityError
from django.contrib.auth.models import User

class movie_all(models.Model):
    movie_code = models.CharField(max_length=255, primary_key=True, default=None)
    rank= models.IntegerField(null=True)
    rank_intensity = models.IntegerField(null=True)
    korean_name = models.CharField(max_length=255, null=True)
    open_date= models.CharField(max_length=255, null=True)
    audiacc=models.CharField(max_length=255, null=True)
    audicnt_showcnt = models.IntegerField(null=True)
    genre = models.CharField(max_length=100)
    running_time = models.CharField(max_length=255, null=True)

class trusted_director(models.Model):
    director= models.CharField(max_length=255, primary_key=True, default=None)
    average_audience=models.IntegerField(null=True)
    audience_showcnt=models.FloatField(null=True)

class trusted_actor(models.Model):
    actor= models.CharField(max_length=255, primary_key=True, default=None)
    number=models.IntegerField(null=True)
    avg_audience=models.IntegerField(null=True)
    audience_showcnt=models.FloatField(null=True)

class music_director(models.Model):
    peoplenm=models.CharField(max_length=255, primary_key=True, default=None)
    work_count=models.IntegerField(null=True)
    average_audiacc=models.IntegerField(null=True)
    audience_showcnt=models.FloatField(null=True)

class comment_worker(models.Model):
    id=models.CharField(max_length=255, primary_key=True, default=None)
    naver_review=models.TextField(null=True)
    same_comment=models.IntegerField(null=True)
    review_score=models.IntegerField(null=True)

# 선택
class choice(models.Model):
    # 선택을 영화와 묶어줌, 영화가 삭제되면 선택도 삭제되게 설정
    movie = models.ForeignKey(movie_all, null=True, on_delete=models.CASCADE)
    # 선택팀 텍스트(토트넘 등등)
    choice_text = models.CharField(max_length=200)
    # 투표수
    votes = models.IntegerField(default=0)

# 댓글
class answer(models.Model):
    # 질문에 해당하는 댓글들을 연결, 질문 지우면 댓글들도 지워짐
    movie = models.ForeignKey(movie_all, null=True, on_delete=models.CASCADE)
    # 댓글 내용 작성 부분
    content = models.TextField()
    # 댓글 작성 날짜
    answer_date = models.DateTimeField(auto_now_add=True)
    # 작성자 속성,기존에 저장된 값들은 null 처리
    author = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

# 유저의 모델 
class user_info(models.Model):
    movie = models.ForeignKey(movie_all, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(choice, null=True, default=None, on_delete=models.CASCADE)
    def save(self, *args, **kwargs):
        # Movie_Ranking 인스턴스가 새로 생성되는 경우에만 choice 인스턴스 생성
        super().save(*args, **kwargs)  # 부모 클래스의 save 메서드 호출로 인스턴스 저장
            # 새로운 Movie_Ranking 인스턴스에 대해 choice 인스턴스 생성
        if not choice.objects.filter(movie=self.movie).exists():
            for i in range(1, 6):  # 1, 2, 3에 대한 choice 인스턴스 생성
                choice.objects.create(movie=self, choice_text=str(i),votes=0)

class movie_info(models.Model):
    movie = models.ManyToManyField(movie_all, related_name='movie_all')
    story = models.TextField(null=True)
    accessible = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    company=models.CharField(max_length=100)
    poster = models.URLField(null=True)

class movie_rating(models.Model):
    movie = models.ForeignKey(movie_all, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(choice, null=True, default=None, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        # 새로운 투표 인스턴스가 생성되는 경우에만 choice 인스턴스 생성
        super().save(*args, **kwargs)  # 부모 클래스의 save 메서드 호출로 인스턴스 저장
            # 이미 해당 영화에 대한 choice 인스턴스가 생성되었는지 확인
        if not choice.objects.filter(movie=self.movie).exists():
            for i in range(1, 6):
                    choice.objects.create(movie=self.movie, choice_text=str(i), votes=0)

            

Django/latest_movie/djan/forms.py
# 폼은 쉽게 말해 페이지 요청시 전달되는 파라미터들을 쉽게 관리하기 위해
# 사용하는 클래스이다. 폼은 필수 파라미터의 값이 누락되지 않았는지, 
# 파라미터의 형식은 적절한지 등을 검증할 목적으로 사용

from django import forms
from djan.models import  answer

class answerForm(forms.ModelForm):
    class Meta:
        model = answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

class MovieSearchForm(forms.Form):
    movie_name = forms.CharField(label='영화 이름', max_length=255)

Django/latest_movie/djan/views.py
from pyexpat.errors import messages
from django.shortcuts import get_object_or_404, redirect,render
from django.utils import timezone
from datetime import datetime as dt
from django.conf import settings
from urllib.parse import quote
from .models import *
import boto3
import io
#페이징으로 페이지에 보이는 영화 갯수를 제한
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.urls import reverse
from PIL import Image
from django.db.models import F,Q
# from django.http import HttpResponseNotAllowed
from .forms import *
from django.contrib.auth.decorators import login_required

# 메인 영화페이지
def main(request,movie_code=None):
    movie_list = movie_all.objects.order_by('rank')
    # S3 이미지 URL 설정
    trend_url1 = f'https://{settings.AWS_STORAGE_BUCKET_NAME}.s3.{settings.AWS_S3_REGION_NAME}.amazonaws.com/naver/naver_trend/trends_group_1.png'
    trend_url2 = f'https://{settings.AWS_STORAGE_BUCKET_NAME}.s3.{settings.AWS_S3_REGION_NAME}.amazonaws.com/naver/naver_trend/trends_group_2.png'
    
    # 템플릿에 URL 전달
    context = {'movie_list': movie_list,'movie_code':movie_code,'trend_url1': trend_url1,'trend_url2': trend_url2}
    return render(request, 'djan/main.html', context)

def ranking(request):
    # 감독별 랭킹 데이터 쿼리
    director_ranking = movie_all.objects.order_by('rank')

    # 배우별 랭킹 데이터 쿼리
    actor_ranking = movie_all.objects.order_by('rank')
    trusted_directors=trusted_director.objects.order_by('-average_audience')
    trusted_actors=trusted_actor.objects.order_by('-avg_audience')
    # 템플릿에 데이터 전달
    context = {
        'director_ranking': director_ranking,
        'actor_ranking': actor_ranking,
        'trusted_directors' : trusted_directors,
        'trusted_actors' : trusted_actors
    }
    return render(request, 'djan/ranking.html', context)

# 모든영화페이지
# 뷰가 호출될 때 URL 매개변수로 movie_code가 제공되지 않으면 movie_code가 None으로 설정됩
def search(request, movie_code=None):
    # 페이지
    # GET 요청의 매개변수 중 'page'라는 이름의 값을 가져옵니다. 
    # 만약 'page' 매개변수가 요청에 없다면 기본값으로 '1'을 사용
    page = request.GET.get('page', '1')
    # GET 요청의 매개변수 중 'kw'라는 이름의 값을 가져옵니다.
    # 만약 검색 요청시 get에 kw가 포함됨
    # 만약 'kw' 매개변수가 요청에 없다면 기본값으로 ''을 사용
    kw = request.GET.get('kw', '')

    # (변경) 전체 영화 모델로 대체해야함
    movie_list = movie_all.objects.all()
    if kw:
        movie_list = movie_list.filter(
            Q(korean_name__icontains=kw) # 제목 검색
        ).distinct()

    # 페이지당 10개씩 보여주기
    paginator = Paginator(movie_list, 10)
    # 현재 페이지의 movie_all 객체들을 page_obj 변수에 저장
    page_obj = paginator.get_page(page)
    # 현재 페이지에 해당하는 movie_all 객체들을 'movie_list'라는 변수로 
    # 템플릿에 전달
    context = {'movie_list': page_obj, 'page' : page, 'kw':kw, 'movie_code':movie_code}
    return render(request, 'djan/search.html', context)

# 상세 영화페이지
def detail(request, movie_code=None):
    # primary key 각 객체를 유일하게 식별하는 주요 식별자입니다.
    # movie_all 모델은 일반적으로 각 질문마다 고유한 pk를 가지고 있습니다. 
    # 사용자가 특정 질문에 접근(get)하려고 할 때, 해당 질문의 pk 값을 URL에서
    # 가져오게 됩니다.
    movie = get_object_or_404(movie_all, pk=movie_code)
    info = movie_info.objects.filter(movie=movie).first()
    rating = None
    average_rate = None
    current_date = timezone.now().date()

    image_url = s3_to_wordcloud(movie_code)
      
    if request.user.is_authenticated:
        rating = movie_rating.objects.filter(movie=movie, user=request.user).first()
        average_rate = average_rating(movie)
    
    #날짜 변환
    open_date = dt.strptime(movie.open_date, '%Y-%m-%d').date()

    allow_vote = open_date <= current_date

    context = {'movie': movie, 'info':info, 'rating': rating, 'movie_code':movie_code, 'average_rate': average_rate, 'allow_vote' : allow_vote, 'image_url': image_url}

    return render(request, 'djan/detail.html', context)

# 댓글 작성할때 로그인 필요
@login_required(login_url='common:login')
# 댓글 작성 (redirect해서 detail로 다시 이동)
# movie_code는 URL 매핑에 의해 그 값이 전달된다. create/2/ 라는 페이지를
# 요청하면 매개변수 movie_code에는 2라는 값이 전달된다.
def answer_create(request, movie_code):
    # 우선 어떤 질문에 달린 댓글인지 알아야함
    movie = get_object_or_404(movie_all, pk=movie_code)
    # 댓글 등록(post)시
    if request.method == "POST":
        # POST 메서드로 전송된 데이터를 이용하여 answerForm 인스턴스를 생성
        form = answerForm(request.POST)
        if form.is_valid():
            # 임시 저장하여 answer 객체를 리턴받는다.
            answer = form.save(commit=False)
            # 작성자(author) 속성에 로그인 계정 저장
            answer.author = request.user
            # 실제 저장을 위해 작성일시를 설정한다.
            answer.answer_date = timezone.now()
            # 해당 질문도 저장
            answer.movie = movie
            answer.save()
            # 데이터베이스 저장후 다시 상세 페이지로 돌아감
            return redirect('djan:detail', movie_code=movie_code)
    #  답변 등록은 POST 방식만 사용되기 때문에 다른방식(GET)은 안됨
    else:
        form = answerForm()
    context = {'movie': movie, 'form': form, 'movie_code':movie_code}
    return render(request, 'djan/detail.html', context)

# 투표(완료시 결과페이지(result)로 이동)

def vote(request, movie_code=None):

    # 로그인하지 않은 사용자는 로그인 페이지로 리다이렉트
    if not request.user.is_authenticated:
        return redirect('common:login')
    
    # 우선 어떤 질문에 달린 투표인지 알아야함
    movie = get_object_or_404(movie_all, pk=movie_code)
    info = movie_info.objects.filter(movie=movie).first()

    user_rating, created = movie_rating.objects.get_or_create(movie=movie, user=request.user)

    if not created:
        average_rate = average_rating(movie)
        return render(request, 'djan/detail.html', {'movie': movie, 'error_message': "이미 투표한 사용자입니다.", 'average_rate': average_rate})

    # 데이터베이스에서 사용자가 해당 질문에 이미 투표했는지 확인
    # 투표했으면 이미 투표했다는 문구 출력

    choice_id = request.POST.get('choice')

    if choice_id is None:
        return render(request, 'djan/detail.html', {'movie': movie, 'error_message': '선택이 없습니다.'})
    try:
        selected_choice = movie.choice_set.get(pk=choice_id)
    #선택 안한경우 처리
    except (KeyError, choice.DoesNotExist):
        return render(request, 'djan/detail.html', {'movie': movie, 'error_message': f"선택이 없습니다. id={request.POST['choice']}"})

    # F는 데이터베이스에서 현재 값을 가져와 필드 값을 업데이트하므로 다른 사용자가
    # 변경한 값을 덮어씌우지 않는다.
    selected_choice.votes = F('votes') + 1
    # 현재 로그인한 사용자를 저장
    selected_choice.user = request.user  
    selected_choice.save()
    
    # 사용자의 투표 항목 업데이트
    user_rating.choice = selected_choice
    user_rating.save()

    # user_info모델에도 투표 내용 저장
    user_info.objects.create(movie=movie, user=request.user, choice=selected_choice)
    average_rate = average_rating(movie)

    return render(request, 'djan/detail.html', {'movie': movie, 'error_message': "투표 완료", 'rating':user_rating, 'info':info, 'average_rate': average_rate})

def average_rating(movie):
    total_vote = 0
    total_rating = 0

    # movie의 choices에서 각 choice에 대한 정보를 가져옴
    for choice in movie.choice_set.all():
        # 각 choice의 투표수와 선택지 별점을 가져옴
        n = choice.votes
        rating = int(choice.choice_text)

        total_vote += n
        total_rating += n * rating

    if total_vote == 0:
        return 0
    
    average_rate = total_rating / total_vote
    return average_rate

    
def s3_to_wordcloud(movie_code=None):
    image_key = f'wordcloud/image/{movie_code}.png'
    image_url = f'https://{settings.AWS_STORAGE_BUCKET_NAME}.s3.{settings.AWS_S3_REGION_NAME}.amazonaws.com/{image_key}'
    image = None
    try:
        # S3 클라이언트 생성
        s3 = boto3.client(
            's3',
            aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
            aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
            region_name=settings.AWS_S3_REGION_NAME
        )

        # 이미지 데이터 가져오기
        response = s3.get_object(Bucket=settings.AWS_STORAGE_BUCKET_NAME, Key=image_key)
        image_data = response['Body'].read()

        # 이미지 열기
        image = Image.open(io.BytesIO(image_data))
        print("Image loaded successfully from S3")

    except Exception as e:
        print(f"Error loading image from S3: {e}")

    if image :
        return image_url
    else:
        return None

# def trend_image(request):
#     # S3 이미지 URL 설정
#     trend_url1 = f'https://{settings.AWS_STORAGE_BUCKET_NAME}.s3.{settings.AWS_S3_REGION_NAME}.amazonaws.com/naver/naver_trend/trends_group_1.png'
#     trend_url2 = f'https://{settings.AWS_STORAGE_BUCKET_NAME}.s3.{settings.AWS_S3_REGION_NAME}.amazonaws.com/naver/naver_trend/trends_group_2.png'
    
#     # 템플릿에 URL 전달
#     context = {'trend_url1': trend_url1,'trend_url2': trend_url2}
#     return render(request, 'main.html', context)

   

Django/latest_movie/templates/djan/detail.html
<!-- 기본 html 형식과 연결-->
{% extends 'base.html' %}
{% block content %}

<!-- 댓글창 스타일 정의 -->
<style>
    .ntextarea {
        width: 1000px; /* 원하는 가로 크기 지정 */
        overflow: auto; /* 스크롤 바가 필요한 경우 나타나도록 설정 */
    }
</style>

<div class="container my-3">
    <!-- 카드 레이아웃 my-3는 상하여백 -->
    <div class="card my-3">
        <h2 class="border-bottom py-2">{{ movie.korean_name }}</h2>
        <div class="row no-gutters">
            <div class="col-md-4">
                <img src="{{ info.poster }}" class="card-img" alt="{{ movie.korean_name }}">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                <!-- 카드 내용 넣는곳 "white-space: pre-line;" 스타일은 텍스트 
                줄바꿈을 유지하도록 합니다.-->
                <!-- py는 상하 패딩을 의미하고, 2는 패딩의 크기를 나타냄. 즉 2의 크기를 가진 패딩 적용 -->
                <!-- <div class="card-text ntextarea" style="white-space: pre-line;">{{ movie.content }}</div> -->
                <div class="d-flex justify-content-end">
                <!-- "badge" 클래스를 사용하여 부가 정보를 표시합니다. "bg-light" 클래스는
                배경색을 밝게 지정하고, "text-dark" 클래스는 텍스트 색상을 어두운 색상지정.
                배지의 패딩을 설정하는 클래스로, 위아래 및 좌우에 모두 2단위의 패딩이 적용-->
                    <div class="badge bg-light text-dark p-2">
                        {{ movie.open_date }}
                    </div>
                </div>
                <div class="card-text ntextarea" style="white-space: pre-line;">
                    <strong>줄거리</strong>  {{ info.story }}

                    <strong> 개봉 날짜</strong> {{ movie.open_date }}

                    <strong>이용 가능 연령</strong> {{ info.accessible }}

                    <strong>장르</strong> {{ movie.genre }}

                    <strong>관람 시간</strong> {{ movie.running_time}}

                    <strong>국가</strong> {{info.country}}

                    <strong>배급사</strong> {{ info.company }}
                    {% if image_url %}
                        <img src="{{ image_url }}" class="card-img" alt="Movie Image">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <br>

    

    <!-- views 에 vote 연결 -->
    {% if user.is_authenticated %}
        {% if not rating and allow_vote %}
            <form action="{% url 'djan:vote' movie.movie_code %}" method="post">
                {% csrf_token %}
                <br>
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <h4>이거 영화관에서 볼만한가요?</h4>
                {% for choice in movie.choice_set.all|dictsort:'choice_text' %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">
                        {{ choice.choice_text }}
                    </label>
                    &nbsp;&nbsp;
                {% endfor %}
                <input type="submit" value="Vote">
            </form>
        {% else %}
            <p>{{ error_message }}</p>
            <h4>현재 투표수</h4>
            <p>
                {% for choice in movie.choice_set.all|dictsort:'choice_text' %}
                    {{ choice.choice_text }} : {{ choice.votes }} 표 &nbsp;&nbsp;
                {% endfor %}
            </p>

            {% if average_rate %}
            <h4>평균 점수</h4> {{ average_rate }}
            {% endif %}
        {% endif %}
    {% else %}
        <!-- 로그인하지 않은 경우 안내 메시지 표시 -->
        <h4>로그인 후 투표하실 수 있습니다.</h4>
    {% endif %}

    <!-- 이미 투표에 참여했다면 -->
    <!--{% if user.is_authenticated and not user_rating %}
        {% if error_message %}
            <p>{{ error_message }}</p>
        {% endif %}
    {% endif %} -->

    <br><br>
    <!-- 현재 댓글창 출력 -->
    <h9 class="border-bottom my-3 py-2">{{movie.answer_set.count}}개의 댓글이 있습니다.</h9>
    <br>
    {% for answer in movie.answer_set.all %}
        [{{ answer.answer_date }}]&nbsp&nbsp&nbsp {{ answer.author.username }} : {{ answer.content }}
        <br>
    {% endfor %}
    <!-- 댓글 등록 -->
    {% if user.is_authenticated %}
        <form action="{% url 'djan:answer_create' movie.movie_code %}" method="post" class="my-3">
            {% csrf_token %}

            <!-- 오류표시 Start -->
            {% include "form_errors.html" %}

            <!-- 하위 요소들을 수평으로 배치하기 위한 Flexbox 레이아웃 -->
            <div class="d-flex">
                <!-- textarea는 우선 로그인 상태에서만 접근가능하고,텍스트 입력란
                ntextarea 클래스는 사용자 정의 CSS 스타일을 적용
                rows 속성은 입력란의 초기 행 수를 1로 설정
                onkeypress 이벤트 핸들러를 등록, 이벤트 타겟은 아래에 정의됨 -->
                <textarea 
                    name="content" id="content" class="form-control" rows="1" onkeypress="submitOnEnter(event)"></textarea>
                <!-- btn btn-primary 클래스는 부트스트랩에서 제공하는 버튼 스타일 -->
                <input type="submit" value="등록" class="btn btn-primary" rows="5">
            </div>
        </form>
    
    <!-- 엔터를 눌러도 댓글이 등록되게 자바스크립트 코드 추가-->
        <script>
            function submitOnEnter(event) {
                // 쉬프트와 함께누르면 일반 줄바꿈으로 인식
                if (event.key === 'Enter' && !event.shiftKey) {
                    // 아무것도 입력하지 않고 등록하려고하면 막음
                    if (event.target.value.trim() === ''){
                        alert('텍스트를 입력하세요.')}
                    // 입력된 텍스트가 비어있지 않은 경우
                    else{
                        // 이벤트(enter)의 기본 동작(submit)을 방지합니다. 
                        event.preventDefault();
                        // 사용자가 직접 제출 버튼을 누르지 않고 JavaScript 코드를
                        // 사용하여 폼을 서버에 제출
                        event.target.form.submit();
                    }
                }
            }
        </script>
    {% else %}
        <p>로그인 후 댓글을 작성할 수 있습니다.</p>
    {% endif %}
</div>
{% endblock %}

Django/latest_movie/templates/djan/main.html
<!-- 영화 일정이 나오는 메인화면입니다. -->

<!-- 기본 html 형식과 연결-->
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2>일간 박스오피스</h2>
    <table class="table">
        <!-- <thead>는 HTML 테이블의 헤더(제목) 부분을 정의 -->
        <thead>
        <!-- <tr> 테이블 내부에서 행을 정의 -->
        <tr class="table-primary">
            <!-- <th> 요소는 테이블의 헤더 셀의 요소 -->
            <th>랭킹</th>
            <th>순위변화</th>
            <th>영화</th>
            <th>누적관객수</th>
            <th>스크린당 관객수</th>
            <th>장르</th>
            <th>상영시간</th>
            <th>개봉일</th>
        </tr>
        </thead>

        <tbody>
        <!-- 만약 영화가 있다면  -->
        {% if movie_list %}
        <!-- 영화를 모두 표시 -->
        {% for movie in movie_list %}
            {% if movie.rank <= 10 %}
                <tr>
                    <!-- <td> 요소는 테이블의 데이터 셀 -->
                    <td>{{ movie.rank }}</td>
                    <td>{{ movie.rank_intensity }}</td>
                    <td>
                        <!-- 영화를 누르면 상세페이지 들어갈수 있다. 상세페이지는
                        movie_code 값들로 링크가 설정돼 있다. -->
                        {% if movie.movie_code %}
                            <a href="{% url 'djan:detail' movie.movie_code %}">{{ movie.korean_name }}</a>
                        {% else %}
                            {{ movie.korean_name }}
                        {% endif %}
                    </td>
                    <td>{{ movie.audiacc }}</td>
                    <td>{{ movie.audicnt_showcnt }}</td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.running_time }}</td>
                    <td>{{ movie.open_date }}</td>

                </tr>
            {% endif %}
        {% endfor %}
        <!-- 영화가 없다면 -->
        {% else %}
        <tr>
            <td colspan="3">영화가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    
    <!-- 탭 메뉴 -->
    <ul class="nav nav-tabs" id="trendTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="trend1-tab" data-toggle="tab" href="#trend1" role="tab" aria-controls="trend1" aria-selected="true">1~5위 검색량</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="trend2-tab" data-toggle="tab" href="#trend2" role="tab" aria-controls="trend2" aria-selected="false">6~10위 검색량</a>
        </li>
    </ul>

    <!-- 탭 컨텐츠 -->
    <div class="tab-content mt-4" id="trendTabContent">
        <div class="tab-pane fade show active" id="trend1" role="tabpanel" aria-labelledby="trend1-tab">
            <h3>한달간 검색 트래픽</h3>
            <div class="image-container">   
                <img src="{{ trend_url1 }}" class="trend-img" alt="1~5위 한달 검색량">
            </div>
        </div>
        <div class="tab-pane fade" id="trend2" role="tabpanel" aria-labelledby="trend2-tab">
            <h3>한달간 검색 트래픽</h3>
            <div class="image-container">
                <img src="{{ trend_url2 }}" class="trend-img" alt="6~10위 한달 검색량">
            </div>
        </div>
    </div>

    <!-- 탭 메뉴 -->

    </div>
</div>

{% endblock %}