Django/latest_movie/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    # 로그인,LoginView 클래스를 사용하여 사용자 인증을 처리합니다.
    path('login/', views.user_login , name='login'),
    # 로그아웃
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # 회원가입요청시 views의 signup 실행
    path('signup/', views.signup, name='signup'),
    # 비밀번호 초기화
    path('password_reset/', views.UserPasswordResetView.as_view(), name="password_reset"),
    # 비밀번호 초기화 링크 전송 성공
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name="password_reset_done"),
]

Django/latest_movie/config/urls.py
from django.contrib import admin
from django.urls import path, include
from djan import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('movie_search/', views.search, name='search'),  # '/' 에 해당되는 path

    path('ranking/', views.ranking, name='ranking'),

    # / 링크가 오면 djan의 urls로
    path('',include('djan.urls')),
    
    path('common/', include('common.urls')),

]

Django/latest_movie/djan/urls.py
from django.urls import path

from . import views

#다른 프로젝트와 꼬이지 않게 이름지정
app_name='djan'

urlpatterns = [
    # '' 요청이 들어오면, view.py 의 main 메서드 연결
    path('', views.main, name='main'),

    # /숫자/ 링크를 입력하면, view.py 의 detail 메서드 연결
    path('<str:movie_code>/', views.detail ,name='detail'),

    # /숫자/vote/ 링크를 입력하면, view.py 의 vote 메서드 연결
    path('<str:movie_code>/vote/', views.vote, name='vote'),
    
    # /answer/create/숫자/ 링크를 입력하면, view.py 의 answer_create 메서드 연결
    # 이건 보통 링크를 입력해 접속하지 않고 투표하면 자동으로 이동한다. 
    path('answer/create/<str:movie_code>/', views.answer_create, name='answer_create'),
]

Django/latest_movie/common/models.py
from django.db import models

Django/latest_movie/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import bcrypt
from django.contrib.auth import authenticate

# 유저 생성 모듈 이용
class UserForm(UserCreationForm):
    # 아래 기본 폼 외에 사용자의 이메일 주소를 입력 받도록 추가로 설정
    email = forms.EmailField(label="이메일")

    class Meta:
        # model은 이 폼이 연결될 사용자 모델을 지정하고, fields는 폼에서 사용할 필드들을 나열
        model = User
        fields = ("username", "password1", "password2", "email")

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)

    # 입력된 데이터를 유효성 검사하기 위해 사용
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)

            if user is None:
                raise forms.ValidationError("사용자명 또는 비밀번호가 올바르지 않습니다.")

        return cleaned_data

Django/latest_movie/common/views.py
# authenticate() 함수는 사용자 인증을 수행합니다. 즉, 제공된 자격 증명이 올바른지 
# 확인하고, 올바른 경우 해당 사용자 객체를 반환
# login() 함수는 사용자를 로그인 상태로 만듭니다. 이는 Django 세션에 사용자 ID를 저장하여
# 사용자를 인증된 상태로 유지하는 데 사용
from django.contrib.auth import authenticate, login
# render() 함수는 특정 템플릿을 사용하여 HTML 페이지를 렌더링하는 데 사용됩니다. 
# redirect() 함수는 클라이언트를 다른 URL로 리디렉션하는 데 사용됨
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.http import JsonResponse
from common.forms import UserForm, LoginForm
from django.contrib.auth.views import ( 
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView,
)                                      
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)

INTERNAL_RESET_URL_TOKEN = 'set-password'
INTERNAL_RESET_SESSION_TOKEN = '_password_reset_token'

def signup(request):
    # urls에서 signup/으로의 주소가 나오면 이 view를 연다. 
    # 이게 열린 상태에서(회원가입 폼에서) POST 입력이 들어오면
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            # 정제된(cleaned) 데이터에서 사용자 이름과 비밀번호를 추출
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password1 = form.cleaned_data.get('password1')
            password2 = form.cleaned_data.get('password2') 

            if User.objects.filter(username=username).exists():
                return JsonResponse({'message': 'USERNAME_ALREADY_EXISTS'}, status=422)

            if User.objects.filter(email=email).exists():
                return JsonResponse({'message': 'EMAIL_ALREADY_EXISTS'}, status=422)

            if password1 != password2:
                return JsonResponse({'message': 'PASSWORD_MISMATCH_ERROR'}, status=422)
            
            form.save()
            # 인증후 로그인 (회원가입 후 자동 로그인되게 설정한것)
            user = authenticate(username=username, password=password1) 
            if user is not None:
                login(request, user)
                return redirect('djan:main')
            # 'main'라는 이름의 URL(메인페이지)로 리다이렉트
    # 사용자가 회원가입 페이지에 처음 접근했을 때(GET 요청) 빈 회원가입 폼 생성
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                # User is valid, log them in
                login(request, user)
                return redirect('djan:main')
            else:
                # Invalid credentials
                form.add_error(None, '사용자명 또는 비밀번호가 올바르지 않습니다.')
    else:
        form = LoginForm()

    return render(request, 'common/login.html', {'form': form})
            
# 비밀번호 잃어버렸을 때
class UserPasswordResetView(PasswordResetView):
    template_name = 'common/password_reset.html'

    # 성공 시 호출할 url
    success_url = reverse_lazy('password_reset_done')
    form_class = PasswordResetForm
    
    def form_valid(self, form):
        # 이메일이 존재해야 발송
        if User.objects.filter(email=self.request.POST.get("email")).exists():
            return super().form_valid(form)
        else:
            return render(self.request, 'common/password_reset_done_fail.html')

# 비밀번호 재설정 링크 보내기 성공           
class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'common/password_reset_done.html'

# 
class UserPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = SetPasswordForm
    success_url=reverse_lazy('password_reset_complete')
    template_name = 'password_reset_confirm.html'

    def form_valid(self, form):
        return super().form_valid(form)

class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'password_reset_complete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['login_url'] = resolve_url(settings.LOGIN_URL)
        return context


                

Django/latest_movie/templates/common/login.html
<!-- djan뿐 아니라 다른곳에도 활용하려고 common 폴더에 적용 -->

{% extends "base.html" %}
{% block content %}
<!-- container와 my-3을 사용하여 간격을 조절하고 컨테이너 스타일을 적용 -->
<div class="container my-3">
    <!-- 로그인 버트 눌렀을때(post) "{% url 'common:login' %}"은 해당 폼이
    제출될 때 어떤 URL로 이동할지를 지정 -->
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <!-- 로그인 성공후 보이지 않는 숨겨진 입력 필드에 next 값이 input됨, 
        {{ next }}는 Django 템플릿 엔진의 문법.해당 템플릿이 렌더링될 때 
        next라는 변수의 값을 사용. 이 경우, 로그인 후에 사용자를 리디렉션할
        페이지의 URL 예> '질문 등록하기'를 눌러 회원가입이 뜬경우 되돌아감-->
        <input type="hidden" name="next" value="{{ next }}">
        <!-- 로그인 에러 템플릿 연결 -->
        {% include "form_errors.html" %}
        <!-- 아이디 입력부분 -->
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <!-- 로그인 실패시 사용자가 이전에 입력한 값을 유지. -->
            <!-- form-control 클래스는 입력 필드의 폭을 100%로 설정하고, 일관된 높이를 제공 -->
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <!-- 비밀번호 입력부분 -->
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <!-- 로그인 버튼 생성 -->
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>

    <p class="mt-3">
        <a href="{% url 'common:password_reset' %}">비밀번호를 잊으셨나요?</a>
    </p>
</div>
{% endblock %}

Django/latest_movie/templates/common/password_reset.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:password_reset' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">전송</button>
    </form>
</div>

Django/latest_movie/templates/common/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <h1>이메일로 비밀번호를 재설정할 수 있는 링크를 보내드렸습니다.</h1>
</div>

Django/latest_movie/templates/common/password_reset_fail.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <h1>존재하지 않는 메일입니다.</h1>
</div>

Django/latest_movie/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <!-- form는 사용자로부터 정보를 수집하는 양식, 사용자가 post 였다면
    signup 뷰에 대한 URL을 동적으로 생성-->
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <!-- 입력값유지 : 가입 실패시 입력한 양식 데이터 중 "username"이라는
            값을 가져와 value에 다시 입력합니다. 값이 없다면 빈 문자열('')을 사용 -->
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}" placeholder="Id">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <!-- type="password" 사용자가 입력한 문자가 화면에 표시되지 않고 마스킹 -->
            <input type="password" class="form-control" name="password1" id="password1"
                value="{{ form.password1.value|default_if_none:'' }}" placeholder="Password">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                value="{{ form.password2.value|default_if_none:'' }}" placeholder="Confirm Password">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                value="{{ form.email.value|default_if_none:'' }}" placeholder="Email">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}