Django/latest_movie/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    # 로그인,LoginView 클래스를 사용하여 사용자 인증을 처리합니다.
    path('login/', views.user_login , name='login'),
    # 로그아웃
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # 회원가입요청시 views의 signup 실행
    path('signup/', views.signup, name='signup'),
    # 비밀번호 초기화
    path('password_reset/', views.UserPasswordResetView.as_view(), name="password_reset"),
    # 비밀번호 초기화 링크 전송 성공
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name="password_reset_done"),
]

Django/latest_movie/config/urls.py
from django.contrib import admin
from django.urls import path, include
from djan import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('movie_search/', views.search, name='search'),  # '/' 에 해당되는 path

    path('ranking/', views.ranking, name='ranking'),

    # / 링크가 오면 djan의 urls로
    path('',include('djan.urls')),
    
    path('common/', include('common.urls')),

]

Django/latest_movie/djan/urls.py
from django.urls import path

from . import views

#다른 프로젝트와 꼬이지 않게 이름지정
app_name='djan'

urlpatterns = [
    # '' 요청이 들어오면, view.py 의 main 메서드 연결
    path('', views.main, name='main'),

    # /숫자/ 링크를 입력하면, view.py 의 detail 메서드 연결
    path('<str:movie_code>/', views.detail ,name='detail'),

    # /숫자/vote/ 링크를 입력하면, view.py 의 vote 메서드 연결
    path('<str:movie_code>/vote/', views.vote, name='vote'),
    
    # /answer/create/숫자/ 링크를 입력하면, view.py 의 answer_create 메서드 연결
    # 이건 보통 링크를 입력해 접속하지 않고 투표하면 자동으로 이동한다. 
    path('answer/create/<str:movie_code>/', views.answer_create, name='answer_create'),
]

Django/latest_movie/templates/base.html
<!-- 표준 html 형식으로 맞춤 -->
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- HTML 문서의 문자 인코딩을 정의합니다. utf-8은 문자 집합(Encoding)으로서, 
        대부분의 텍스트와 문자를 처리하는 데 사용되는 광범위한 유니코드 문자 세트 -->
    <meta charset="utf-8">
    <!-- 뷰포트는 사용자가 웹 페이지를 보는 디바이스 화면의 영역을 나타냅니다. 
    width=device-width는 뷰포트의 너비를 디바이스의 화면 너비에 맞추라는 의미 
    
    initial-scale=1 웹 페이지가 초기 로딩 시 100% 배율로 표시되도록 설정
    shrink-to-fit=no 뷰포트가 작을 때 텍스트가 자동으로 축소되지 않도록 설정-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 부트 스트랩 CSS 연결 -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>Hello!</title>

</head>

<body>
<!-- 네비게이션바 html 연결 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<!--메뉴버튼 사용위해 Bootstrap JS 연결 -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

Django/latest_movie/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
    <div class="alert alert-danger">
        <!-- 필드 에러 -->
        {% for field in form %}
            <!-- 폼에 오류가 있는지 확인 -->
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}

        {% endfor %}
        <!-- 넌필드 오류 -->
        {% for error in form.non_field_errors %}
        <div>
            <strong>{{ error }}</strong>
        </div>
        {% endfor %}
    </div>
{% endif %}

<!-- 
필드 오류: 사용자가 폼에 입력한 데이터가 필드에 대한 기대와 맞지 않을 때
넌-필드 오류 : 여러 필드 간의 관계나 폼 전체에 영향을 주는 오류입니다. 
예를 들어, 비밀번호와 비밀번호 확인 필드가 일치하지 않는 경우 -->

Django/latest_movie/templates/navbar.html
<!-- 네비게이션 바 입니다. -->
<!-- 
navbar: 네비게이션 바 컨테이너를 나타내는 클래스입니다.
navbar-expand-lg: 브라우저의 너비가 일정 이상인 경우에만 네비게이션 바를 확장하는 클래스입니다. 여기서 "lg"는 라지(대형) 화면을 의미합니다.
navbar-light: 밝은 배경색을 가진 네비게이션 바를 나타내는 클래스입니다.
bg-light: 밝은 배경색을 가지도록 배경을 설정하는 클래스입니다.
border-bottom: 네비게이션 바의 하단에 경계선을 추가하는 클래스입니다. -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <!-- 네비게이션 바의 내용을 감싸고, 화면의 전체 너비를 차지하도록 합니다. 
    이를 통해 네비게이션 바의 요소들이 반응형으로 화면에 잘 맞춰지도록 할 수 있습니다. -->
    <div class="container-fluid">
        <!-- 네비게이션 바 브랜드 로고 -->
        <a class="navbar-brand" href="{% url 'djan:main' %}"><h1>극장서 뭐 보지?</h1></a>
        <!-- 네비게이션 바의 햄버거 버튼을 스타일링, 클릭 가능한 버튼 표시-->
        <!-- 
        class="navbar-toggler": 네비게이션 바의 햄버거 버튼을 스타일링하기 위한 Bootstrap 클래스
        type="button": 버튼 요소를 나타내며, 클릭 가능한 버튼임을 명시합니다.
        
        data-bs-toggle="collapse": Bootstrap의 collapse 컴포넌트를 사용하여 요소를 
        접거나 펼칠 수 있도록 트리거하는 역할을 합니다.

        data-bs-target="#navbarSupportedContent": 햄버거 버튼이 클릭되었을 때 펼쳐질 
        요소의 식별자를 지정합니다. 여기서는 #navbarSupportedContent로 지정되어 있는데, 
        이는 네비게이션 바의 메뉴들이 토글될 대상을 나타냅니다.

        aria-controls="navbarSupportedContent": 햄버거 버튼이 제어하는 컨텐츠 영역을 
        명시합니다. 스크린 리더 및 보조 기술에 접근성을 제공합니다.

        aria-expanded="false": 햄버거 버튼이 클릭되었을 때 펼쳐지지 않은 상태임을 
        나타냅니다. 초기에는 메뉴가 접혀있기 때문에 false로 설정됩니다.

        aria-label="Toggle navigation": 햄버거 버튼의 목적을 설명하는 텍스트입니다. 
        스크린 리더를 통해 사용자에게 제공됩니다. -->
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <!-- 햄버거 아이콘 -->
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- 네비게이션 바의 메뉴들 -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- 왼쪽 메뉴 아이템들 -->
            <!-- navbar-nav: 네비게이션 바의 메뉴를 스타일링하는 Bootstrap 클래스입니다.
            me-auto: 오른쪽으로부터 최대한 멀리 위치하도록 메뉴 아이템을 배치하는 클래스
            Flexbox 레이아웃에서 메뉴 아이템을 오른쪽으로 밀어내어 왼쪽에 정렬될 수 있도록함
            
            mb-2 mb-lg-0: 마진을 조절하는 클래스입니다. mb-2는 모바일 화면에서 아래쪽으로 
            2단위의 마진을 추가하고, mb-lg-0는 라지(대형) 화면에서 아래쪽 마진을 0으로 
            설정합니다. -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djan:main' %}">
                        <h5>메인</h5>
                    </a>
                </li>
                <li class="nav-item">
                    <!-- 영화검색 링크 -->
                    <a class="nav-link" href="{% url 'search' %}">
                        <h5>영화검색</h5>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ranking' %}">
                        <h5>각종영화랭킹</h5>
                    </a>
                </li>
            </ul>

            <!-- (왼쪽) 마진을 자동으로 설정해, 오른쪽에 출력되게함 -->
            <ul class="navbar-nav ms-auto">
                <!-- 사용자가 로그인한 경우 -->
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <!-- 로그아웃 링크 -->
                        <a class="nav-link" href="{% url 'common:logout' %}">
                            <!-- 사용자 이름 (로그아웃) -->
                            {{ user.username }} (로그아웃)
                        </a>
                    </li>
                <!-- 사용자가 로그인하지 않은 경우 -->
                {% else %}
                    <li class="nav-item">
                        <!-- 로그인 링크 -->
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    </li>
                    <!-- 사용자가 로그인하지 않은 경우에만 회원가입 링크가 보이도록 함 -->
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <!-- 회원가입 링크 -->
                            <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                        </li>
                    {% endif %}
                {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>